### ISSUE TITLE
Failed due to an invalid structure

### ISSUE THREAD

**Issue by BitraAI** [bneijt/ipfs-video-kodi#4]
Install from zip file in Kodi is failing due to invalid structure due to version in addon.xml. While run it, it writes the following error in kodi.log.

EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'ModuleNotFoundError'>
                                                   Error Contents: No module named 'ipfs'
                                                   Traceback (most recent call last):
                                                     File "\AppData\Roaming\Kodi\addons\plugin.video.ipfs\main.py", line 14, in <module>
                                                       import ipfs
                                                   ModuleNotFoundError: No module named 'ipfs'
                                                   -->End of Python script error report<--

**Comment by BitraAI** [comment]
I have fixed the issue...Here are the modifications and cleanup.
1. Added version in addon.xml - <addon id="plugin.video.ipfs" version="" name="IPFS" provider-name="ipfs.video">
2. Moved main.py and ipfs folder to parent folder and removed ipfs_video_kodi folder. 
3. Deleted .github/workflows and test folders, .gitignore, Makefile, poetry.lock, pyproject.toml
4. Added gateway https://ipfs.infura.io in settings.xml
5. Removed https://gateway.pinata.cloud/ in settings.xml as it is slow
6. The zip file name is plugin.video.ipfs.zip

**Comment by anand-bitra** [comment]
Please add this code to take multiple rootCIDs.
settings.xml :
<?xml version="1.0" encoding="utf-8" standalone="yes"?>
<settings>
    <category label="5">
        <setting label="32000" type="labelenum" id="rootCid" values="rootCid1|rootCid2|rootCid3|rootCid4|rootCid5"/>
        <setting label="32001" type="labelenum" id="ipfsGateway" default="https://ipfs.io" values="http://127.0.0.1:8080|https://ipfs.io|https://dweb.link|https://gateway.ipfs.io|https://ipfs.infura.io"/>
	<setting label="rootCid1" type="text" id="rootCid1" default="QmYHDhsgUgdKSAimguGC92MzQ8VNFHZw3yp6kAHwiXCFLm"/>
	<setting label="rootCid2" type="text" id="rootCid2" default="Set rootCid2"/>
	<setting label="rootCid3" type="text" id="rootCid3" default="Set rootCid3"/>
	<setting label="rootCid4" type="text" id="rootCid4" default="Set rootCid4"/>
	<setting label="rootCid5" type="text" id="rootCid5" default="Set rootCid5"/>
    </category>
</settings>

main.py : Next the line 21
if _rootCid == "rootCid1":
	_rootCid = xbmcplugin.getSetting(_handle, "rootCid1")
elif _rootCid == "rootCid2":
	_rootCid = xbmcplugin.getSetting(_handle, "rootCid2")
elif _rootCid == "rootCid3":
	_rootCid = xbmcplugin.getSetting(_handle, "rootCid3")
elif _rootCid == "rootCid4":
	_rootCid = xbmcplugin.getSetting(_handle, "rootCid4")
elif _rootCid == "rootCid5":
	_rootCid = xbmcplugin.getSetting(_handle, "rootCid5")

**Comment by anand-bitra** [comment]
settings.xml :
<?xml version="1.0" encoding="utf-8" standalone="yes"?>
<settings>
    <category label="5">
        <setting label="32000" type="labelenum" id="rootCid" values="rootCid1|rootCid2|rootCid3|rootCid4|rootCid5"/>
        <setting label="32001" type="labelenum" id="ipfsGateway" default="https://ipfs.io" values="http://127.0.0.1:8080|https://ipfs.io|https://dweb.link|https://gateway.ipfs.io|https://ipfs.infura.io"/>
	<setting label="rootCid1" type="text" id="rootCid1" default="QmYHDhsgUgdKSAimguGC92MzQ8VNFHZw3yp6kAHwiXCFLm"/>
	<setting label="rootCid2" type="text" id="rootCid2" default="Set rootCid2"/>
	<setting label="rootCid3" type="text" id="rootCid3" default="Set rootCid3"/>
	<setting label="rootCid4" type="text" id="rootCid4" default="Set rootCid4"/>
	<setting label="rootCid5" type="text" id="rootCid5" default="Set rootCid5"/>
    </category>
</settings>

**Comment by bneijt** [comment]
I have added a line to the documentation to make more clear that the zip of the branch source code itself is not a valid kodi package.
Use `make build` to build a proper plugin zip or download a zip from the releases page.
