### ISSUE TITLE
Add multiple rootCIDs

### ISSUE THREAD

**Issue by BitraAI** [bneijt/ipfs-video-kodi#5]
Please add this code to take multiple rootCIDs.
settings.xml :
<?xml version="1.0" encoding="utf-8" standalone="yes"?>
<settings>
    <category label="5">
        <setting label="32000" type="labelenum" id="rootCid" values="rootCid1|rootCid2|rootCid3|rootCid4|rootCid5"/>
        <setting label="32001" type="labelenum" id="ipfsGateway" default="https://ipfs.io" values="http://127.0.0.1:8080|https://ipfs.io|https://dweb.link|https://gateway.ipfs.io|https://ipfs.infura.io"/>
	<setting label="rootCid1" type="text" id="rootCid1" default="QmYHDhsgUgdKSAimguGC92MzQ8VNFHZw3yp6kAHwiXCFLm"/>
	<setting label="rootCid2" type="text" id="rootCid2" default="Set rootCid2"/>
	<setting label="rootCid3" type="text" id="rootCid3" default="Set rootCid3"/>
	<setting label="rootCid4" type="text" id="rootCid4" default="Set rootCid4"/>
	<setting label="rootCid5" type="text" id="rootCid5" default="Set rootCid5"/>
    </category>
</settings>

main.py : Next the line 21
if _rootCid == "rootCid1":
	_rootCid = xbmcplugin.getSetting(_handle, "rootCid1")
elif _rootCid == "rootCid2":
	_rootCid = xbmcplugin.getSetting(_handle, "rootCid2")
elif _rootCid == "rootCid3":
	_rootCid = xbmcplugin.getSetting(_handle, "rootCid3")
elif _rootCid == "rootCid4":
	_rootCid = xbmcplugin.getSetting(_handle, "rootCid4")
elif _rootCid == "rootCid5":
	_rootCid = xbmcplugin.getSetting(_handle, "rootCid5")

**Comment by bneijt** [comment]
This will still only have one active root cid at a time, I think it makes more sense to allow for multiple root cid's that are all active at the same time, but that would mean we have to merge the file tree and I could not come up with a way to solve collisions.

Do you have any ideas on what we should be doing here? Maybe we should add support for ipns?

**Comment by bneijt** [comment]
Released 0.0.7 https://github.com/bneijt/ipfs-video-kodi/releases/tag/0.0.7

Hope this closes all the issues you posted, if not, feel free to post more issues.

Thank you for testing this plugin!
