### ISSUE TITLE
Does it stream directly from ipfs node?

### ISSUE THREAD

**Issue by hikenshi** [bneijt/ipfs-video-kodi#9]
Hi,
Does it stream directly from ipfs node or stream only from ipfs gateway?

**Comment by bneijt** [comment]
This plugin only points Kodi to a stream on a HTTP gateway to IPFS.

You can start and run go-ipfs locally and point the plugin to that installation, but the plugin does not start a node for you.

Feel free to open this issue again if you have any more questions along this line or open a feature request if you have a feature requested.
